version: '3'

# start docker compose
# docker-compose up -d

# stop docker compose
# docker-compose stop

# stop and remove docker container
# docker-compose down

services:
  mongo:
    image: mongo:4
    volumes:
      - ./docker/db/mongodb:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

networks:
  elk:
    driver: bridge
